# Generated by Django 6.1 on 2026-09-01 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_grp_backend", "0022_default_protocol_templates"),
        ("django_grp_org", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Ziel")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Beschreibung"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("education", "Erziehung und Entwicklung"),
                            ("school", "Schule und Ausbildung"),
                            ("health", "Gesundheit"),
                            ("social", "Soziale Beziehungen"),
                            ("family", "Familie und Herkunft"),
                            ("independence", "Verselbständigung"),
                            ("other", "Sonstiges"),
                        ],
                        default="education",
                        max_length=20,
                        verbose_name="Bereich",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("in_progress", "In Arbeit"),
                            ("achieved", "Erreicht"),
                            ("dropped", "Nicht weiterverfolgt"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Stand",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(blank=True, null=True, verbose_name="Zieltermin"),
                ),
                ("position", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Hilfeplanziel",
                "verbose_name_plural": "Hilfeplanziele",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="CaseFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="Aktenzeichen",
                    ),
                ),
                (
                    "youth_office",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Zuständiges Jugendamt",
                    ),
                ),
                (
                    "case_manager",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name der zuständigen Person im Jugendamt",
                        max_length=120,
                        verbose_name="Fallführung Jugendamt",
                    ),
                ),
                ("opened_on", models.DateField(verbose_name="Aufnahme")),
                (
                    "closed_on",
                    models.DateField(blank=True, null=True, verbose_name="Abschluss"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Laufend"),
                            ("paused", "Ruhend"),
                            ("closed", "Abgeschlossen"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="Notizen"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_files",
                        to="django_grp_org.provider",
                        verbose_name="Träger",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_files",
                        to="django_grp_backend.resident",
                        verbose_name="Bewohner",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_files",
                        to="django_grp_org.employee",
                        verbose_name="Bezugsbetreuung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fallakte",
                "verbose_name_plural": "Fallakten",
                "ordering": ["-opened_on"],
            },
        ),
        migrations.CreateModel(
            name="CaseParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("youth_office", "Jugendamt"),
                            ("guardian", "Sorgeberechtigt"),
                            ("custodian", "Vormund"),
                            ("parent", "Elternteil"),
                            ("child", "Kind / Jugendliche:r"),
                            ("school", "Schule"),
                            ("therapy", "Therapie / Medizin"),
                            ("facility", "Einrichtung"),
                            ("other", "Sonstige"),
                        ],
                        max_length=20,
                        verbose_name="Rolle",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "organisation",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Telefon oder E-Mail",
                        max_length=150,
                        verbose_name="Kontakt",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "case_file",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="django_grp_care.casefile",
                        verbose_name="Fallakte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beteiligte:r",
                "verbose_name_plural": "Beteiligte",
                "ordering": ["kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="HelpMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Maßnahme")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Beschreibung"
                    ),
                ),
                (
                    "responsible",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Person, Dienst oder Stelle",
                        max_length=120,
                        verbose_name="Zuständig",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z. B. wöchentlich, 14-tägig",
                        max_length=80,
                        verbose_name="Rhythmus",
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="Abgeschlossen"),
                ),
                ("position", models.IntegerField(default=0)),
                (
                    "goal",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measures",
                        to="django_grp_care.helpgoal",
                        verbose_name="Ziel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maßnahme",
                "verbose_name_plural": "Maßnahmen",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="HelpPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Fassung"),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        choices=[
                            ("27", "§ 27 Hilfe zur Erziehung"),
                            ("29", "§ 29 Soziale Gruppenarbeit"),
                            ("30", "§ 30 Erziehungsbeistand"),
                            ("31", "§ 31 Sozialpädagogische Familienhilfe"),
                            ("32", "§ 32 Erziehung in einer Tagesgruppe"),
                            ("33", "§ 33 Vollzeitpflege"),
                            ("34", "§ 34 Heimerziehung"),
                            ("35", "§ 35 Intensive sozialpädagogische Einzelbetreuung"),
                            ("35a", "§ 35a Eingliederungshilfe"),
                            ("41", "§ 41 Hilfe für junge Volljährige"),
                        ],
                        max_length=5,
                        verbose_name="Rechtsgrundlage",
                    ),
                ),
                (
                    "help_form",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z. B. Familienanaloge Wohngruppe, Tagesgruppe",
                        max_length=150,
                        verbose_name="Hilfeform",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Gültig ab")),
                (
                    "valid_to",
                    models.DateField(blank=True, null=True, verbose_name="Gültig bis"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("active", "Gültig"),
                            ("superseded", "Fortgeschrieben"),
                            ("closed", "Beendet"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "situation",
                    models.TextField(
                        blank=True, default="", verbose_name="Ausgangslage"
                    ),
                ),
                (
                    "review_date",
                    models.DateField(
                        blank=True,
                        help_text="Erscheint als Frist im Kalender",
                        null=True,
                        verbose_name="Nächste Fortschreibung",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_file",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_plans",
                        to="django_grp_care.casefile",
                        verbose_name="Fallakte",
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="successors",
                        to="django_grp_care.helpplan",
                        verbose_name="Vorherige Fassung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hilfeplan",
                "verbose_name_plural": "Hilfepläne",
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="helpgoal",
            name="help_plan",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="django_grp_care.helpplan",
                verbose_name="Hilfeplan",
            ),
        ),
        migrations.CreateModel(
            name="CaseMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("help_plan", "Hilfeplangespräch"),
                            ("case_conference", "Fallkonferenz"),
                            ("handover", "Übergabegespräch"),
                            ("other", "Sonstiges"),
                        ],
                        default="help_plan",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Ort"
                    ),
                ),
                (
                    "participants",
                    models.TextField(
                        blank=True, default="", verbose_name="Teilnehmende"
                    ),
                ),
                (
                    "minutes",
                    models.TextField(blank=True, default="", verbose_name="Verlauf"),
                ),
                (
                    "decisions",
                    models.TextField(blank=True, default="", verbose_name="Beschlüsse"),
                ),
                (
                    "next_meeting",
                    models.DateField(
                        blank=True, null=True, verbose_name="Nächster Termin"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case_file",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="django_grp_care.casefile",
                        verbose_name="Fallakte",
                    ),
                ),
                (
                    "help_plan",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="django_grp_care.helpplan",
                        verbose_name="Hilfeplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fallgespräch",
                "verbose_name_plural": "Fallgespräche",
                "ordering": ["-date"],
            },
        ),
    ]
