# Generated by Django 6.1 on 2026-09-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_org", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=100, verbose_name="Datensatzart"),
                ),
                (
                    "object_id",
                    models.CharField(max_length=40, verbose_name="Datensatz"),
                ),
                ("label", models.CharField(max_length=200, verbose_name="Bezeichnung")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Angelegt"),
                            ("update", "Geändert"),
                            ("delete", "Gelöscht"),
                        ],
                        max_length=10,
                        verbose_name="Vorgang",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text='{"feld": ["vorher", "nachher"]}',
                        null=True,
                        verbose_name="Änderungen",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Benutzer"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zeitpunkt"),
                ),
            ],
            options={
                "verbose_name": "Änderungsprotokoll",
                "verbose_name_plural": "Änderungsprotokoll",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["model", "object_id"],
                        name="django_grp__model_dd009b_idx",
                    )
                ],
            },
        ),
    ]
