# Generated by Django 6.1 on 2026-09-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grp_org', '0002_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='access_level',
            field=models.CharField(choices=[('admin', 'Mitarbeiter'), ('specialist', 'Fachkraft'), ('assistant', 'Aushilfe / Azubi')], default='specialist', help_text='Mitarbeiter: verwaltet Stammdaten, Personal und Dienstplan. Fachkraft: schreibt in den eigenen Gruppen. Aushilfe / Azubi: liest in den eigenen Gruppen.', max_length=20, verbose_name='Zugriff'),
        ),
    ]
