# Generated by Django 6.1 on 2026-09-02 16:44

import django_grp_backend.functions
import django_grp_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grp_org', '0005_default_master_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=django_grp_backend.models.RandomizedFileName(), validators=[django_grp_backend.functions.validate_image], verbose_name='Foto'),
        ),
    ]
