# Generated by Django 6.1 on 2026-09-04 17:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grp_org', '0006_employee_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('name', models.CharField(max_length=100, verbose_name='Anlass')),
                ('factor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = ganzer Feiertag, 0,5 = halber Tag (etwa Heiligabend)', max_digits=3, verbose_name='Verbleibender Arbeitstag')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('provider', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='django_grp_org.provider', verbose_name='Träger')),
            ],
            options={
                'verbose_name': 'Feiertag',
                'verbose_name_plural': 'Feiertage',
                'ordering': ['date'],
                'unique_together': {('provider', 'date')},
            },
        ),
    ]
