# Generated by Django 6.1 on 2026-09-10 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_org", "0007_holiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="pay_step",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Leer, wenn die Stufe nicht geführt wird",
                null=True,
                verbose_name="Stufe",
            ),
        ),
        migrations.CreateModel(
            name="PayGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Bezeichnung")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Wofür die Gruppe gilt",
                        max_length=200,
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Kleinere Zahl steht weiter oben",
                        verbose_name="Reihenfolge",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Abgeschaltet verschwindet sie aus der Auswahl, bestehende Verträge behalten sie",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pay_grades",
                        to="django_grp_org.provider",
                        verbose_name="Träger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entgeltgruppe",
                "verbose_name_plural": "Entgeltgruppen",
                "ordering": ["position", "name"],
                "unique_together": {("provider", "name")},
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="pay_grade_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Aus den Stammdaten des Trägers",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="django_grp_org.paygrade",
                verbose_name="Entgeltgruppe",
            ),
        ),
        migrations.CreateModel(
            name="PayGradeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.PositiveSmallIntegerField(verbose_name="Stufe")),
                (
                    "monthly_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Bei Vollzeit, in Euro",
                        max_digits=9,
                        verbose_name="Monatsentgelt",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Gültig ab")),
                (
                    "pay_grade",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="django_grp_org.paygrade",
                        verbose_name="Entgeltgruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entgeltstufe",
                "verbose_name_plural": "Entgeltstufen",
                "ordering": ["pay_grade", "step", "-valid_from"],
                "unique_together": {("pay_grade", "step", "valid_from")},
            },
        ),
        migrations.CreateModel(
            name="SurchargeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("night", "Nachtarbeit"),
                            ("saturday", "Samstagsarbeit"),
                            ("sunday", "Sonntagsarbeit"),
                            ("holiday", "Feiertagsarbeit"),
                        ],
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="0 lassen, wenn die Lohnabrechnung den Satz selbst kennt",
                        max_digits=5,
                        verbose_name="Zuschlag in Prozent",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Welches Tarifwerk, welche Fundstelle",
                        max_length=200,
                        verbose_name="Anmerkung",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surcharge_rates",
                        to="django_grp_org.provider",
                        verbose_name="Träger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zuschlagssatz",
                "verbose_name_plural": "Zuschlagssätze",
                "ordering": ["kind"],
                "unique_together": {("provider", "kind")},
            },
        ),
    ]
