# Generated by Django 6.1 on 2026-09-10 06:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_org", "0009_entgeltgruppen_zuordnen"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="monthly_hours_factor",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("4.348"),
                help_text="Wochenstunden mal diesem Faktor ergeben die Monatsstunden",
                max_digits=5,
                verbose_name="Monatsfaktor",
            ),
        ),
    ]
