# Generated by Django 6.1 on 2026-09-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_care", "0001_initial"),
        ("django_grp_org", "0010_traeger_monatsfaktor"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="case_file",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Nur für Fallführung und externe Lesekräfte",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="django_grp_care.casefile",
                verbose_name="Fallakte",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Wofür die Zuweisung gilt – bei externen Zugängen der Anlass",
                max_length=200,
                verbose_name="Anmerkung",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roles",
                to="django_grp_org.site",
                verbose_name="Standort",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[
                    ("executive", "Geschäftsführung"),
                    ("facility_lead", "Einrichtungsleitung"),
                    ("group_lead", "Gruppenleitung"),
                    ("duty_planner", "Dienstplanung"),
                    ("specialist", "Fachkraft"),
                    ("assistant", "Ergänzungskraft"),
                    ("case_lead", "Fallführung"),
                    ("administration", "Verwaltung"),
                    ("external_reader", "Externe Lesekraft"),
                ],
                max_length=20,
                verbose_name="Rolle",
            ),
        ),
    ]
