# Generated by Django 6.1 on 2026-09-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, default='', max_length=200, verbose_name='Server')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='Port')),
                ('use_tls', models.BooleanField(default=True, help_text='Der uebliche Weg auf Port 587', verbose_name='STARTTLS')),
                ('use_ssl', models.BooleanField(default=False, help_text='Nur fuer Port 465 - nicht zusammen mit STARTTLS', verbose_name='SSL')),
                ('username', models.CharField(blank=True, default='', max_length=200, verbose_name='Benutzername')),
                ('password_encrypted', models.TextField(blank=True, default='', editable=False)),
                ('from_address', models.EmailField(blank=True, default='', max_length=254, verbose_name='Absenderadresse')),
                ('from_name', models.CharField(blank=True, default='Gruppenprotokoll', max_length=120, verbose_name='Absendername')),
                ('timeout_seconds', models.PositiveIntegerField(default=15, verbose_name='Zeitgrenze in Sekunden')),
                ('enabled', models.BooleanField(default=False, help_text='Aus heisst: Mails werden im Postausgang festgehalten, aber nicht verschickt', verbose_name='Versand aktiv')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-Mail-Einstellung',
                'verbose_name_plural': 'E-Mail-Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.EmailField(max_length=254, verbose_name='Empfänger')),
                ('subject', models.CharField(max_length=250, verbose_name='Betreff')),
                ('body', models.TextField(verbose_name='Inhalt')),
                ('kind', models.CharField(choices=[('test', 'Testmail'), ('absence_decided', 'Abwesenheit entschieden'), ('plan_published', 'Dienstplan veröffentlicht'), ('swap', 'Diensttausch'), ('todo_due', 'Aufgabe wird fällig')], default='test', max_length=30, verbose_name='Anlass')),
                ('status', models.CharField(choices=[('queued', 'Wartet'), ('sending', 'Wird verschickt'), ('sent', 'Verschickt'), ('failed', 'Fehlgeschlagen'), ('skipped', 'Übersprungen')], default='queued', max_length=20, verbose_name='Stand')),
                ('error', models.TextField(blank=True, default='', verbose_name='Fehler')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Versuche')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Verschickt am')),
            ],
            options={
                'verbose_name': 'Postausgang',
                'verbose_name_plural': 'Postausgang',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='django_grp__status_b0326c_idx')],
            },
        ),
    ]
