# Generated by Django 6.1 on 2026-09-04 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grp_mail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsettings',
            name='push_enabled',
            field=models.BooleanField(default=False, help_text='Benachrichtigungen auf Telefon und Rechner, zusätzlich zur E-Mail', verbose_name='Push aktiv'),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='vapid_private_key_encrypted',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='vapid_public_key',
            field=models.TextField(blank=True, default='', help_text='Wird an den Browser gegeben – kein Geheimnis', verbose_name='Öffentlicher Schlüssel'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True, verbose_name='Adresse')),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, default='', help_text='Damit man in der Liste erkennt, welches Gerät gemeint ist', max_length=250, verbose_name='Gerät')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Konto')),
            ],
            options={
                'verbose_name': 'Push-Anmeldung',
                'verbose_name_plural': 'Push-Anmeldungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
