# Generated by Django 6.1 on 2026-09-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grp_mail', '0002_mailsettings_push_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='kind',
            field=models.CharField(choices=[('test', 'Testmail'), ('absence_decided', 'Abwesenheit entschieden'), ('plan_published', 'Dienstplan veröffentlicht'), ('swap', 'Diensttausch'), ('todo_due', 'Aufgabe wird fällig'), ('password_reset', 'Passwort zurücksetzen')], default='test', max_length=30, verbose_name='Anlass'),
        ),
    ]
