# Generated by Django 6.1 on 2026-09-01 06:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_grp_org", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Bezeichnung")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("vacation", "Urlaub"),
                            ("sick", "Krankheit"),
                            ("training", "Fortbildung"),
                            ("special", "Sonderurlaub"),
                            ("unpaid", "Unbezahlt"),
                            ("other", "Sonstiges"),
                        ],
                        default="vacation",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "reduces_vacation",
                    models.BooleanField(
                        default=True, verbose_name="Vom Urlaubskonto abziehen"
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Krankmeldungen brauchen meist keine Genehmigung",
                        verbose_name="Genehmigungspflichtig",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#fda769", max_length=9, verbose_name="Farbe"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_types",
                        to="django_grp_org.provider",
                        verbose_name="Träger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abwesenheitsart",
                "verbose_name_plural": "Abwesenheitsarten",
                "ordering": ["provider", "name"],
            },
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Von")),
                ("end_date", models.DateField(verbose_name="Bis")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Beantragt"),
                            ("approved", "Genehmigt"),
                            ("rejected", "Abgelehnt"),
                            ("cancelled", "Zurückgezogen"),
                        ],
                        default="requested",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Anmerkung"
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_note",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_absences",
                        to="django_grp_org.employee",
                        verbose_name="Entschieden von",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="django_grp_org.employee",
                        verbose_name="Mitarbeitende",
                    ),
                ),
                (
                    "absence_type",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="django_grp_duty.absencetype",
                        verbose_name="Art",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abwesenheit",
                "verbose_name_plural": "Abwesenheiten",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="DutyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Jahr")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Monat")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("published", "Veröffentlicht"),
                            ("locked", "Abgeschlossen"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_plans",
                        to="django_grp_org.department",
                        verbose_name="Bereich",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dienstplan",
                "verbose_name_plural": "Dienstpläne",
                "ordering": ["-year", "-month"],
                "unique_together": {("department", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="ShiftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Bezeichnung")),
                (
                    "short_code",
                    models.CharField(
                        help_text="Erscheint im Dienstplanraster",
                        max_length=6,
                        verbose_name="Kürzel",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Beginn")),
                ("end_time", models.TimeField(verbose_name="Ende")),
                (
                    "break_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Pause in Minuten"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#abc270", max_length=9, verbose_name="Farbe"
                    ),
                ),
                (
                    "is_night",
                    models.BooleanField(
                        default=False,
                        help_text="Zählt für Nachtzuschläge und Ruhezeitprüfung",
                        verbose_name="Nachtdienst",
                    ),
                ),
                (
                    "is_on_call",
                    models.BooleanField(
                        default=False,
                        help_text="Wird als Bereitschaftszeit gebucht, nicht als volle Arbeitszeit",
                        verbose_name="Bereitschaft",
                    ),
                ),
                (
                    "counts_specialist",
                    models.BooleanField(
                        default=True, verbose_name="Zählt für Fachkraftquote"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_types",
                        to="django_grp_org.provider",
                        verbose_name="Träger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dienstart",
                "verbose_name_plural": "Dienstarten",
                "ordering": ["provider", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "is_substitute",
                    models.BooleanField(
                        default=False,
                        help_text="Kurzfristig übernommen, etwa bei Krankheit",
                        verbose_name="Vertretung",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shifts",
                        to="django_grp_org.employee",
                        verbose_name="Mitarbeitende",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="django_grp_duty.dutyplan",
                        verbose_name="Dienstplan",
                    ),
                ),
                (
                    "shift_type",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="django_grp_duty.shifttype",
                        verbose_name="Dienstart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dienst",
                "verbose_name_plural": "Dienste",
                "ordering": ["date", "shift_type__start_time"],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("start_time", models.TimeField(verbose_name="Beginn")),
                ("end_time", models.TimeField(verbose_name="Ende")),
                (
                    "break_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Pause in Minuten"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("work", "Arbeitszeit"),
                            ("on_call", "Bereitschaft"),
                            ("training", "Fortbildung"),
                            ("travel", "Reisezeit"),
                        ],
                        default="work",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="Freigegeben"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="django_grp_org.employee",
                        verbose_name="Mitarbeitende",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_entries",
                        to="django_grp_duty.shift",
                        verbose_name="Dienst",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zeitbuchung",
                "verbose_name_plural": "Zeitbuchungen",
                "ordering": ["-date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TimeAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Jahr")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Monat")),
                (
                    "target_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=7,
                        verbose_name="Soll",
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=7,
                        verbose_name="Ist",
                    ),
                ),
                (
                    "carry_over",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=7,
                        verbose_name="Übertrag aus Vormonat",
                    ),
                ),
                (
                    "on_call_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=7,
                        verbose_name="Bereitschaft",
                    ),
                ),
                (
                    "night_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=7,
                        verbose_name="Nachtstunden",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Abgeschlossen am"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_accounts",
                        to="django_grp_org.employee",
                        verbose_name="Mitarbeitende",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zeitkonto",
                "verbose_name_plural": "Zeitkonten",
                "ordering": ["-year", "-month"],
                "unique_together": {("employee", "year", "month")},
            },
        ),
    ]
