# Generated by Django 6.1 on 2026-09-01 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_duty", "0001_initial"),
        ("django_grp_org", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftSwap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offered", "Angeboten"),
                            ("accepted", "Angenommen"),
                            ("confirmed", "Bestätigt"),
                            ("declined", "Abgelehnt"),
                            ("withdrawn", "Zurückgezogen"),
                        ],
                        default="offered",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Grund"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_swaps",
                        to="django_grp_org.employee",
                        verbose_name="Übernimmt",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_swaps",
                        to="django_grp_org.employee",
                        verbose_name="Bestätigt von",
                    ),
                ),
                (
                    "offered_by",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offered_swaps",
                        to="django_grp_org.employee",
                        verbose_name="Bietet an",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swaps",
                        to="django_grp_duty.shift",
                        verbose_name="Dienst",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diensttausch",
                "verbose_name_plural": "Diensttausche",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("wish", "Wunsch"),
                            ("block", "Möchte nicht"),
                            ("unavailable", "Nicht verfügbar"),
                        ],
                        default="wish",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="django_grp_org.employee",
                        verbose_name="Mitarbeitende",
                    ),
                ),
                (
                    "shift_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Leer lassen, wenn der ganze Tag gemeint ist",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="django_grp_duty.shifttype",
                        verbose_name="Dienstart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dienstwunsch",
                "verbose_name_plural": "Dienstwünsche",
                "ordering": ["date"],
                "unique_together": {("employee", "date", "shift_type")},
            },
        ),
    ]
