# Generated by Django 6.1 on 2026-09-02 12:32

"""Ende einer Zeitbuchung darf offen bleiben.

Fuer die Stempeluhr auf dem Dashboard: wer stempelt, legt eine Buchung mit
Beginn und ohne Ende an. Erst das Abstempeln traegt das Ende nach.

Eine laufende Buchung zaehlt nirgends mit - TimeEntry.hours gibt dafuer 0
zurueck, damit weder Zeitkonto noch Lohnabrechnung mit geratenen Stunden
rechnen. ShiftType.end_time bleibt bewusst Pflicht: eine Dienstart ohne Ende
hat keine Dauer.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_duty", "0002_shiftswap_shiftpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Ende"),
        ),
    ]
