# Generated by Django 6.1 on 2026-09-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grp_duty', '0003_timeentry_open_end'),
        ('django_grp_org', '0005_default_master_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.TimeField(blank=True, null=True, verbose_name='Ab')),
                ('ends_at', models.TimeField(blank=True, null=True, verbose_name='Bis')),
                ('minimum_staff', models.PositiveIntegerField(default=2, verbose_name='Mindestens Personen')),
                ('minimum_specialists', models.PositiveIntegerField(default=1, help_text='0, wenn hier keine Fachkraft vorgeschrieben ist', verbose_name='Davon Fachkräfte')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('department', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='staffing_requirements', to='django_grp_org.department', verbose_name='Bereich')),
                ('shift_type', models.ForeignKey(blank=True, db_constraint=False, help_text='Leer lassen, wenn stattdessen ein Uhrzeit-Fenster gilt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffing_requirements', to='django_grp_duty.shifttype', verbose_name='Dienstart')),
            ],
            options={
                'verbose_name': 'Besetzungsvorgabe',
                'verbose_name_plural': 'Besetzungsvorgaben',
                'ordering': ['department', 'starts_at', 'shift_type'],
            },
        ),
    ]
