# Generated by Django 6.1 on 2026-09-03 11:11

"""Bereitschaft als Anteil statt als Ja/Nein.

is_on_call konnte nur die ganze Schicht als Bereitschaft markieren. Ein
24-Stunden-Dienst mit sechs Stunden Nachtbereitschaft liess sich damit nicht
abbilden: entweder wurden alle vierundzwanzig Stunden halbiert (zwoelf statt
einundzwanzig) oder gar keine.

Diese Migration aendert an bestehenden Daten NICHTS am Ergebnis: wo bisher
die ganze Schicht Bereitschaft war, steht danach die volle Netto-Dauer in
on_call_minutes. Wer den Anteil korrigieren will, tut das bewusst in der
Oberflaeche - eine Migration, die Arbeitszeiten stillschweigend neu rechnet,
waere hier das Letzte, was jemand gebrauchen kann.
"""

from datetime import datetime, timedelta

from django.db import migrations, models


def netto_minuten(dienstart) -> int:
    """Wie models.ShiftType.gross_minutes, aber fuer die historische Fassung."""
    basis = datetime(2000, 1, 1)
    start = basis.replace(
        hour=dienstart.start_time.hour, minute=dienstart.start_time.minute
    )
    ende = basis.replace(hour=dienstart.end_time.hour, minute=dienstart.end_time.minute)
    if ende <= start:
        ende += timedelta(days=1)
    brutto = int((ende - start).total_seconds() // 60)
    return max(0, brutto - dienstart.break_minutes)


def uebernehmen(apps, schema_editor):
    ShiftType = apps.get_model("django_grp_duty", "ShiftType")
    for dienstart in ShiftType.objects.filter(is_on_call=True):
        dienstart.on_call_minutes = netto_minuten(dienstart)
        dienstart.save(update_fields=["on_call_minutes"])


def zurueck(apps, schema_editor):
    ShiftType = apps.get_model("django_grp_duty", "ShiftType")
    ShiftType.objects.filter(on_call_minutes__gt=0).update(is_on_call=True)


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_duty", "0005_default_shift_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="shifttype",
            name="on_call_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Anteil der Dienstzeit, der Bereitschaft ist. 0 = keine. Beispiel 24-Stunden-Dienst mit sechs Stunden Nachtbereitschaft: 360.",
                verbose_name="Davon Bereitschaft in Minuten",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="on_call_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Leer lassen - dann gilt der Anteil der Dienstart",
                verbose_name="Davon Bereitschaft in Minuten",
            ),
        ),
        migrations.AlterField(
            model_name="shifttype",
            name="is_on_call",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Ergibt sich aus der Bereitschaftszeit, nicht selbst zu setzen",
                verbose_name="Enthält Bereitschaft",
            ),
        ),
        migrations.RunPython(uebernehmen, zurueck),
    ]
