# Generated by Django 5.1.4 on 2024-12-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0002_alter_resident_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocol",
            name="date_added",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="protocol_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="resident",
            name="moved_in_since",
            field=models.DateField(auto_now=True),
        ),
    ]
