# Generated by Django 5.1.4 on 2024-12-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0003_alter_protocol_date_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocol",
            name="date_added",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="protocol_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="resident",
            name="moved_in_since",
            field=models.DateField(),
        ),
    ]
