# Generated by Django 5.1.4 on 2024-12-13 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0008_protocolpresence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="group_members",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
