# Generated by Django 5.1.4 on 2024-12-17 10:43

import django_grp_backend.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0010_alter_group_group_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                validators=[django_grp_backend.functions.validate_image],
            ),
        ),
    ]
