# Generated by Django 5.1.4 on 2024-12-17 12:06

import django_grp_backend.functions
import django_grp_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0011_alter_resident_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=django_grp_backend.models.RandomizedFileName(),
                validators=[django_grp_backend.functions.validate_image],
            ),
        ),
    ]
