# Generated by Django 5.0.6 on 2025-11-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0014_group_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("ready", "Bereit zum Export"),
                    ("exported", "Exportiert"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
