# Generated by Django 5.0.6 on 2025-12-04 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0015_protocol_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("resident", "Bewohner"),
                            ("protocol", "Protokolle"),
                            ("group", "Gruppen"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("read", "Lesezugriff"),
                            ("write", "Schreibzugriff"),
                            ("delete", "Löschzugriff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_grp_backend.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "group", "resource"],
                "unique_together": {("user", "group", "resource", "permission")},
            },
        ),
    ]
