# Generated by Django 5.2.8 on 2025-12-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0016_userpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="exported_file",
            field=models.FileField(blank=True, null=True, upload_to="exports/"),
        ),
    ]
