# Generated by Django 5.2.8 on 2025-12-15 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0017_protocol_exported_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtocolTodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "was",
                    models.TextField(
                        help_text="What needs to be done", verbose_name="Was"
                    ),
                ),
                (
                    "wer",
                    models.CharField(
                        help_text="Who is responsible",
                        max_length=255,
                        verbose_name="Wer",
                    ),
                ),
                (
                    "wann",
                    models.DateTimeField(
                        help_text="When it's due", verbose_name="Wann"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.IntegerField(default=0)),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todos",
                        to="django_grp_backend.protocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protocol Todo",
                "verbose_name_plural": "Protocol Todos",
                "ordering": ["position", "wann"],
            },
        ),
    ]
