# Generated by Django 5.2.8 on 2025-12-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0018_protocoltodo"),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocoltodo',
            old_name='was',
            new_name='what',
        ),
        migrations.RenameField(
            model_name='protocoltodo',
            old_name='wer',
            new_name='who',
        ),
        migrations.RenameField(
            model_name='protocoltodo',
            old_name='wann',
            new_name='when',
        ),
    ]
