# Generated by Django 6.1 on 2026-08-31 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0020_alter_group_pdf_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="protocoltodo",
            options={
                "ordering": ["position", "when"],
                "verbose_name": "Protocol Todo",
                "verbose_name_plural": "Protocol Todos",
            },
        ),
        migrations.AddField(
            model_name="protocol",
            name="topic",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Thema oder Anlass des Gruppenangebots",
                max_length=200,
                verbose_name="Thema",
            ),
        ),
        migrations.AddField(
            model_name="protocolitem",
            name="data",
            field=models.JSONField(
                blank=True,
                help_text='Bei kind="table": {"columns": [...], "rows": [[...], ...]}',
                null=True,
                verbose_name="Strukturierter Inhalt",
            ),
        ),
        migrations.AddField(
            model_name="protocolitem",
            name="kind",
            field=models.CharField(
                choices=[("text", "Freitext"), ("table", "Tabelle")],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="protocoltodo",
            name="what",
            field=models.TextField(
                help_text="What needs to be done", verbose_name="What"
            ),
        ),
        migrations.AlterField(
            model_name="protocoltodo",
            name="when",
            field=models.DateTimeField(help_text="When it's due", verbose_name="When"),
        ),
        migrations.AlterField(
            model_name="protocoltodo",
            name="who",
            field=models.CharField(
                help_text="Who is responsible", max_length=255, verbose_name="Who"
            ),
        ),
        migrations.CreateModel(
            name="ProtocolObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("course", "Verlauf"),
                            ("observation", "Beobachtung"),
                            ("agreement", "Vereinbarung"),
                        ],
                        default="course",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(verbose_name="Text")),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "protocol",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="django_grp_backend.protocol",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Leer lassen für die Gruppe insgesamt",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_grp_backend.resident",
                        verbose_name="Bewohner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verlaufseintrag",
                "verbose_name_plural": "Verlaufseinträge",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Beschreibung",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Leer lassen, damit die Vorlage für alle Gruppen gilt",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_templates",
                        to="django_grp_backend.group",
                        verbose_name="Gruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protokollvorlage",
                "verbose_name_plural": "Protokollvorlagen",
                "ordering": ["position", "name"],
            },
        ),
        migrations.AddField(
            model_name="protocol",
            name="template",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Protokolltyp, aus dem die Tagesordnung erzeugt wurde",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="protocols",
                to="django_grp_backend.protocoltemplate",
                verbose_name="Vorlage",
            ),
        ),
        migrations.CreateModel(
            name="ProtocolTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Überschrift")),
                ("position", models.IntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[("text", "Freitext"), ("table", "Tabelle")],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "hint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Wird als Platzhalter im Editor angezeigt",
                        max_length=200,
                        verbose_name="Hinweis",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True, default="", verbose_name="Vorbelegter Text"
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        blank=True,
                        help_text='Bei kind="table", z. B. ["Aufgabe", "Verantwortung", "Termin"]',
                        null=True,
                        verbose_name="Spalten",
                    ),
                ),
                (
                    "rows",
                    models.IntegerField(
                        default=3,
                        help_text="Vorbereitete Zeilen der Tabelle",
                        verbose_name="Leerzeilen",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="django_grp_backend.protocoltemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vorlagen-Baustein",
                "verbose_name_plural": "Vorlagen-Bausteine",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "was_present",
                    models.BooleanField(default=True, verbose_name="Teilgenommen"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Anmerkung"
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="django_grp_backend.protocol",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_grp_backend.resident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teilnahme",
                "verbose_name_plural": "Teilnahmen",
                "ordering": ["resident__last_name", "resident__first_name"],
                "unique_together": {("protocol", "resident")},
            },
        ),
    ]
