# Generated by Django 6.1 on 2026-09-01 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grp_backend', '0022_default_protocol_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('guardian', 'Erziehungsberechtigt'), ('mother', 'Mutter'), ('father', 'Vater'), ('custodian', 'Vormund'), ('relative', 'Angehörige:r'), ('youth_office', 'Jugendamt'), ('doctor', 'Ärztin / Arzt'), ('school', 'Schule / Kita'), ('therapy', 'Therapie'), ('other', 'Sonstige')], default='guardian', max_length=20, verbose_name='Rolle')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('relationship', models.CharField(blank=True, default='', help_text='Freitext, falls die Rolle es nicht genau trifft', max_length=80, verbose_name='Verhältnis')),
                ('organisation', models.CharField(blank=True, default='', max_length=120, verbose_name='Organisation')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, default='', max_length=40, verbose_name='Mobil')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-Mail')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='Anschrift')),
                ('has_custody', models.BooleanField(default=False, help_text='Darf über Schule, Medizin und Aufenthalt mitentscheiden', verbose_name='Sorgeberechtigt')),
                ('is_emergency', models.BooleanField(default=False, help_text='Wird im Notfall zuerst angerufen', verbose_name='Notfallkontakt')),
                ('note', models.TextField(blank=True, default='', help_text='Erreichbarkeit, Absprachen, Umgangsregelungen', verbose_name='Hinweis')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='django_grp_backend.resident', verbose_name='Bewohner:in')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakte',
                'ordering': ['-is_emergency', 'position', 'id'],
                'indexes': [models.Index(fields=['resident', 'position'], name='django_grp__residen_ae0b12_idx')],
            },
        ),
    ]
