# Generated by Django 6.1 on 2026-09-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grp_backend', '0024_teammeeting_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='Zwei bis vier Zeichen für Plaketten und enge Listen, etwa „6a“. Leer lassen: dann wird es aus dem Namen abgeleitet.', max_length=8, verbose_name='Kürzel'),
        ),
    ]
