# Generated by Django 6.1 on 2026-09-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_grp_backend', '0025_group_short_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
