# Generated by Django 6.1 on 2026-09-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_grp_backend', '0028_fremdschluessel_wiederherstellen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Gruppe', 'verbose_name_plural': 'Gruppen'},
        ),
        migrations.AlterModelOptions(
            name='protocol',
            options={'ordering': ['-protocol_date', '-id'], 'verbose_name': 'Protokoll', 'verbose_name_plural': 'Protokolle'},
        ),
        migrations.AlterModelOptions(
            name='protocolpresence',
            options={'ordering': ['id'], 'verbose_name': 'Anwesenheit', 'verbose_name_plural': 'Anwesenheiten'},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['last_name', 'first_name', 'id'], 'verbose_name': 'Bewohner', 'verbose_name_plural': 'Bewohner'},
        ),
    ]
