# Generated by Django 6.1 on 2026-09-09 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0030_teambesprechung_nach_vorn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("food", "Lebensmittel"),
                            ("medication", "Medikament"),
                            ("insect", "Insektenstich"),
                            ("material", "Material oder Stoff"),
                            ("other", "Sonstiges"),
                        ],
                        default="food",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Woran genau, z. B. Erdnuss oder Penicillin",
                        max_length=120,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Leicht"),
                            ("moderate", "Mittel"),
                            ("severe", "Schwer"),
                        ],
                        default="moderate",
                        max_length=20,
                        verbose_name="Schwere",
                    ),
                ),
                (
                    "reaction",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Was passiert, woran man es erkennt",
                        max_length=200,
                        verbose_name="Reaktion",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Was im Ernstfall zu tun ist",
                        max_length=200,
                        verbose_name="Hinweis",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="django_grp_backend.resident",
                        verbose_name="Bewohner:in",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allergie",
                "verbose_name_plural": "Allergien",
                "ordering": ["-severity", "name"],
            },
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("photo_internal", "Fotos intern"),
                            ("photo_external", "Fotos veröffentlichen"),
                            ("outing", "Ausflüge und Fahrten"),
                            ("swimming", "Schwimmen"),
                            ("medical", "Ärztliche Behandlung"),
                            ("medication", "Medikamentengabe"),
                            ("data_school", "Austausch mit der Schule"),
                            ("data_therapy", "Austausch mit Therapie und Medizin"),
                            ("transport", "Mitfahrt im Dienstfahrzeug"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=30,
                        verbose_name="Gegenstand",
                    ),
                ),
                (
                    "granted",
                    models.BooleanField(
                        default=True,
                        help_text="Nein heißt: ausdrücklich nicht erteilt. Das ist etwas anderes als „nicht gefragt“.",
                        verbose_name="Erteilt",
                    ),
                ),
                (
                    "granted_by",
                    models.CharField(
                        help_text="Wer unterschrieben hat",
                        max_length=120,
                        verbose_name="Erteilt von",
                    ),
                ),
                ("granted_on", models.DateField(verbose_name="Erteilt am")),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Leer heißt: bis zum Widerruf",
                        null=True,
                        verbose_name="Gültig bis",
                    ),
                ),
                (
                    "revoked_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="Widerrufen am"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Einschränkungen, Absprachen, wo das Papier liegt",
                        max_length=200,
                        verbose_name="Vermerk",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="django_grp_backend.resident",
                        verbose_name="Bewohner:in",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einwilligung",
                "verbose_name_plural": "Einwilligungen",
                "ordering": ["subject", "-granted_on"],
            },
        ),
    ]
