# Generated by Django 6.1 on 2026-09-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0031_bewohnerakte_allergie_einwilligung"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Grundlage des Alters in der amtlichen Statistik",
                null=True,
                verbose_name="Geburtsdatum",
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Weiblich"),
                    ("male", "Männlich"),
                    ("diverse", "Divers"),
                ],
                default="",
                help_text="Leer lassen, wenn keine Angabe vorliegt",
                max_length=10,
                verbose_name="Geschlecht",
            ),
        ),
    ]
