# Generated by Django 6.1 on 2026-09-10 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0032_bewohner_geburtsdatum_geschlecht"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="school",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Der zweite Lebensmittelpunkt und der häufigste Anlass für Absprachen",
                max_length=150,
                verbose_name="Schule",
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="school_class",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Klasse"
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="school_contact",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name und Erreichbarkeit",
                max_length=150,
                verbose_name="Klassenleitung",
            ),
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("admission", "Aufnahme"),
                            ("discharge", "Entlassung"),
                        ],
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Was")),
                (
                    "done_on",
                    models.DateField(blank=True, null=True, verbose_name="Erledigt am"),
                ),
                (
                    "done_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Erledigt von",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="django_grp_backend.resident",
                        verbose_name="Bewohner:in",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklistenpunkt",
                "verbose_name_plural": "Checklistenpunkte",
                "ordering": ["kind", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("absence", "Unerlaubte Abwesenheit"),
                            ("violence", "Gewalt"),
                            ("self_harm", "Selbstgefährdung"),
                            ("accident", "Unfall"),
                            ("police", "Polizeieinsatz"),
                            ("suspicion", "Verdacht nach § 8a"),
                            ("substance", "Suchtmittel"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="Zeitpunkt")),
                (
                    "description",
                    models.TextField(
                        help_text="Was geschehen ist, sachlich", verbose_name="Hergang"
                    ),
                ),
                (
                    "immediate_action",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Was unmittelbar getan wurde",
                        verbose_name="Sofortmaßnahme",
                    ),
                ),
                (
                    "participants",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Wer dabei war, wer verständigt wurde",
                        max_length=300,
                        verbose_name="Beteiligte",
                    ),
                ),
                (
                    "reported_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Landesjugendamt, Jugendamt, Polizei",
                        max_length=200,
                        verbose_name="Gemeldet an",
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gemeldet am"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("reported", "Gemeldet"),
                            ("closed", "Abgeschlossen"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Stand",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="django_grp_backend.group",
                        verbose_name="Gruppe",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aufgenommen von",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leer lassen, wenn es die Gruppe insgesamt betrifft",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="django_grp_backend.resident",
                        verbose_name="Bewohner:in",
                    ),
                ),
            ],
            options={
                "verbose_name": "Besonderes Vorkommnis",
                "verbose_name_plural": "Besondere Vorkommnisse",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.CharField(
                        help_text="Wonach im Zweifel gesucht wird",
                        max_length=120,
                        verbose_name="Wirkstoff",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Handelsname, wie er auf der Packung steht",
                        max_length=120,
                        verbose_name="Präparat",
                    ),
                ),
                (
                    "dose",
                    models.CharField(
                        help_text="z. B. 10 mg oder 1 Tablette",
                        max_length=80,
                        verbose_name="Dosis",
                    ),
                ),
                (
                    "times",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Uhrzeiten als Liste, z. B. ["08:00", "20:00"]',
                        verbose_name="Zeitpunkte",
                    ),
                ),
                (
                    "as_needed",
                    models.BooleanField(
                        default=False,
                        help_text="Ohne festen Zeitpunkt. Dann gehört die Bedingung in den Hinweis.",
                        verbose_name="Bedarfsmedikation",
                    ),
                ),
                (
                    "prescribed_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Praxis oder Ärztin",
                        max_length=120,
                        verbose_name="Verordnet von",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Ab")),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        help_text="Leer, solange es weiter gegeben wird",
                        null=True,
                        verbose_name="Bis",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bedingung, Höchstmenge, was zu beachten ist",
                        max_length=200,
                        verbose_name="Hinweis",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="django_grp_backend.resident",
                        verbose_name="Bewohner:in",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medikament",
                "verbose_name_plural": "Medikamente",
                "ordering": ["as_needed", "agent"],
            },
        ),
        migrations.CreateModel(
            name="MedicationAdministration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        help_text="Der Zeitpunkt aus dem Plan; bei Bedarfsmedikation die Gabe selbst",
                        verbose_name="Vorgesehen",
                    ),
                ),
                (
                    "given_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gegeben um"
                    ),
                ),
                (
                    "given_by_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Der Name zum Zeitpunkt der Gabe. Er steht hier fest, damit der Nachweis lesbar bleibt, wenn das Konto später gelöscht wird.",
                        max_length=120,
                        verbose_name="Name",
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="Menge"
                    ),
                ),
                (
                    "skipped",
                    models.BooleanField(
                        default=False,
                        help_text="Eine ausgelassene Gabe ist auch eine Gabe",
                        verbose_name="Ausgelassen",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bei ausgelassener Gabe erforderlich",
                        max_length=200,
                        verbose_name="Grund",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corrects",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zeigt auf die Zeile, die gemeint war",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrections",
                        to="django_grp_backend.medicationadministration",
                        verbose_name="Korrigiert",
                    ),
                ),
                (
                    "given_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medication_administrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gegeben von",
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrations",
                        to="django_grp_backend.medication",
                        verbose_name="Medikament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gabe",
                "verbose_name_plural": "Gaben",
                "ordering": ["-scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="PocketMoneyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("credit", "Gutschrift"),
                            ("payout", "Auszahlung"),
                            ("correction", "Korrektur"),
                        ],
                        default="payout",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Gutschrift positiv, Auszahlung positiv — die Art entscheidet das Vorzeichen",
                        max_digits=8,
                        verbose_name="Betrag",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "recorded_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Erfasst von",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pocket_money",
                        to="django_grp_backend.resident",
                        verbose_name="Bewohner:in",
                    ),
                ),
            ],
            options={
                "verbose_name": "Barbetrag-Buchung",
                "verbose_name_plural": "Barbetrag-Buchungen",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResidentAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("home", "Heimfahrt"),
                            ("holiday", "Ferien"),
                            ("clinic", "Klinik"),
                            ("unauthorised", "Unerlaubt abwesend"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Von")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leer, solange die Abwesenheit läuft",
                        null=True,
                        verbose_name="Bis",
                    ),
                ),
                (
                    "counts_as_occupied",
                    models.BooleanField(
                        default=True,
                        help_text="Heimfahrt und Ferien zählen üblicherweise weiter als belegt, eine Klinikunterbringung ab einer gewissen Dauer nicht. Prüfen Sie das gegen die Entgeltvereinbarung.",
                        verbose_name="Zählt als belegt",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="django_grp_backend.resident",
                        verbose_name="Bewohner:in",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abwesenheit",
                "verbose_name_plural": "Abwesenheiten",
                "ordering": ["-start_date"],
            },
        ),
    ]
