# Generated by Django 6.1.1 on 2026-09-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0034_volltextindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocoltodo",
            name="done_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Leer heißt: noch offen",
                null=True,
                verbose_name="Erledigt am",
            ),
        ),
        migrations.AddField(
            model_name="protocoltodo",
            name="done_by",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Erledigt von"
            ),
        ),
    ]
