# Generated by Django 6.1.1 on 2026-09-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0036_medikation_in_teambesprechung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "Freitext"),
                    ("table", "Tabelle"),
                    ("medication", "Medikationsübersicht"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="protocoltemplateitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "Freitext"),
                    ("table", "Tabelle"),
                    ("medication", "Medikationsübersicht"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
