# Generated by Django 6.1.1 on 2026-09-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0039_medikation_vor_die_faelle"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="pdf_bottom",
            field=models.FloatField(default=56, verbose_name="Abstand unten"),
        ),
        migrations.AddField(
            model_name="group",
            name="pdf_left",
            field=models.FloatField(default=56, verbose_name="Abstand links"),
        ),
        migrations.AddField(
            model_name="group",
            name="pdf_right",
            field=models.FloatField(default=56, verbose_name="Abstand rechts"),
        ),
        migrations.AddField(
            model_name="group",
            name="pdf_top",
            field=models.FloatField(default=56, verbose_name="Abstand oben"),
        ),
    ]
