"""
Der zweite Faktor als Tabelle.

Optional fuer alle, Pflicht fuer Konten, die verwalten duerfen. Die Tabelle
ist leer, solange niemand ihn einschaltet - ein bestehender Aufbau merkt von
dieser Migration nichts.
"""

# Generated by Django 6.1.1 on 2026-09-11 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0041_tagesprotokoll_vor_teambesprechung"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZweiterFaktor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geheim_verschluesselt",
                    models.TextField(blank=True, default="", editable=False),
                ),
                (
                    "bestaetigt_am",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leer, solange die Einrichtung nicht abgeschlossen ist",
                        null=True,
                        verbose_name="Bestätigt am",
                    ),
                ),
                (
                    "letzter_schritt",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("zuletzt_verwendet", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zweiter_faktor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zweiter Faktor",
                "verbose_name_plural": "Zweite Faktoren",
            },
        ),
    ]
