"""
Die Rechtematrix je Person.

Die Tabelle ist leer, und das ist der Punkt: solange fuer eine Person keine
Zeile existiert, entscheidet ihre bisherige Zugriffsstufe weiter. Ein
bestehender Aufbau merkt von dieser Migration nichts, bis jemand die erste
Matrix ausfuellt.
"""

# Generated by Django 6.1.1 on 2026-09-12 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_grp_backend", "0042_zweiter_faktor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rechtezuweisung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aktion",
                    models.CharField(
                        help_text="Die Kennung aus rechte.py, etwa doku.protokolle",
                        max_length=40,
                        verbose_name="Merkmal",
                    ),
                ),
                (
                    "stufe",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Kein Zugriff"),
                            (1, "Lesen"),
                            (2, "Lesen und schreiben"),
                        ],
                        default=0,
                        verbose_name="Stufe",
                    ),
                ),
                ("geaendert_am", models.DateTimeField(auto_now=True)),
                (
                    "geaendert_von",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Wer die Matrix zuletzt gesetzt hat",
                        max_length=120,
                        verbose_name="Geändert von",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rechtezuweisungen",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechtezuweisung",
                "verbose_name_plural": "Rechtezuweisungen",
                "ordering": ["user_id", "aktion"],
                "unique_together": {("user", "aktion")},
            },
        ),
    ]
